### ISSUE TITLE
Failed while attempting to sync values: Unexpected end of JSON input

### ISSUE THREAD

**Issue by re-sounding** [statsig-io/node-js-server-sdk#10]
statsig-node v4.16.1. Node + Typescript + Webpack.

I have no dynamic configuration, gates, or experiments setup. When calling `logEvent` with `localMode: true`, `Failed while attempting to sync values: Unexpected end of JSON input` is logged to the console. 

The debugger points to this line, where the value of `specsString` is `''`. This does not happen when `localMode: false`.
![Screenshot 2022-06-20 at 19 35 12](https://user-images.githubusercontent.com/3074801/174661509-669564b1-8bc6-4fcc-a9b4-d660f689661d.png)

Additional context: I'm using Webpack and had to jump through a few hoops to get fetch and Response to be available globally. Let me know if I can provide any further information.

**Comment by tore-statsig** [comment]
Ah thanks for the report - we will get this fixed up

**Comment by tore-statsig** [comment]
This should be fixed in `v4.17.0` by this change: https://github.com/statsig-io/node-js-server-sdk/commit/1d2c2a66d58d808c68ca8330c526f79202fcb511
