### ISSUE TITLE
Edge Runtime support

### ISSUE THREAD

**Issue by dferber90** [statsig-io/node-js-server-sdk#17]
I'm trying to use this package in a Next.js [Edge API Route](https://nextjs.org/docs/api-routes/edge-api-routes) or a [Middleware](https://nextjs.org/docs/advanced-features/middleware).

These two places use a special [Edge Runtime](https://edge-runtime.vercel.sh) which has constraints different from Node.js, for example `Buffer` does not exist there.

At the moment `getHashedName` and `computeUserHash` are using the `sha.js` package which internally uses `Buffer`. This prevents the package from being usable from [Edge Runtime](https://edge-runtime.vercel.sh).

Both Edge Runtime supports and Node.js support SubtleCrypto [mdn](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto), ([edge-runtime](https://edge-runtime.vercel.sh/features/available-apis#:~:text=WritableStreamDefaultWriter-,Web%20Crypto%20APIs,-crypto)) so it might be possible to switch both functions to this implementation.

This change would allow the package to be used from Next.js Middleware and Edge API Routes.

**Comment by tore-statsig** [comment]
Interesting, thanks for the detailed issue.  We will look into it
