### ISSUE TITLE
TypeError - nodeFetch.apply is not a function

### ISSUE THREAD

**Issue by tejaswitandel** [statsig-io/node-js-server-sdk#38]
![image](https://github.com/statsig-io/node-js-server-sdk/assets/18231191/6e84d7a6-d901-40b0-97fd-fa428bbc4773)
My initialisation is already successful but when I calling "checkGateSync" or "checkGate" its always return false where in console value was true. 
What's the issue? 
StatsIg version - 5.12.0

**Comment by tore-statsig** [comment]
What environment are you running this in?  Is this in a node app, or on an serverless/edge function somewhere?

**Comment by litofish** [comment]
I had the same issue this past week and was about to open a similar thread. For me I found the issue was that this SDK is not compatible with next.js version 14+ and it only worked once I downgraded to the latest next.js version 13. I think it may be because [next.js 14+ requires a minimum Node.js version of 18.17](https://nextjs.org/blog/next-14).

Would like to know if there are any ways I could resolve this to get the SDK working with the latest next.js version, or if there are plans to upgrade the SDK to have it work with next 14

**Comment by tore-statsig** [comment]
Thanks for the details - we didn't have any plans, but I can look into support for node 18/nextjs 14

**Comment by tejaswitandel** [comment]
> What environment are you running this in? Is this in a node app, or on an serverless/edge function somewhere?
I'm using in development of vscode extension. 
Nodejs - 18

**Comment by tore-statsig** [comment]
Thanks for confirming - sounds like it is a node 18 compatibility issue.  We're looking into it

**Comment by tore-statsig** [comment]
Is your node app running on an edge/lambda function?  Or using webpack?  Is it a browser js environment or a server js environment?

**Comment by tejaswitandel** [comment]
Webpack and with server js.

**Comment by tore-statsig** [comment]
Mmm I wonder if its related to weback.  I just tried to repro with node 18, more specifically:

```
$ node --version
v18.18.2
```

And everything worked fine.  I'm going to try a small nextjs app now

**Comment by tore-statsig** [comment]
Okay I think I know whats going on here.  If you are using statsig with nextjs, you need to be careful where you are using which type of SDK.  Statsig offers two types of SDKs - server sdks, and client SDKs.  Next js encompasses both server aspects (you can write a custom server) and client side (react app).

The statsig-node server SDK is intended for server environments and will not work in your react application.

I've confirmed the `statsig-node` sdk works just fine in nextjs 14 and node 18, provided you are using it in the server - like a custom server here:

https://nextjs.org/docs/pages/building-your-application/configuring/custom-server


It also sounds like @tejaswitandel is building a browser extension. This is definitely a better fit for our client side, single user environment SDKs.   You can find a good overview of client SDKs here:

https://docs.statsig.com/client/introduction

You are probably looking for either the `statsig-js` or `statsig-react` client side SDKs.  Hope this helps

**Comment by tore-statsig** [comment]
This was actually a valid bug we were eventually able to reproduce, patched in this version

https://www.npmjs.com/package/statsig-node/v/5.13.1
