### ISSUE TITLE
Feature request: ability to clear all local overrides

### ISSUE THREAD

**Issue by neil176** [statsig-io/node-js-server-sdk#41]
It's possible I'm missing some functionality that enables this, but what I'd like to be able to do is reset overrides. Context for this is that it's common for engineers to write some tests with the general structure of:
- "when feature is enabled, X happens"
- "when feature is disabled, Y happens"

The existing interface of `overrideGate` allows doing this imperatively, but requires state management in keeping track of what gate gets turned on for what user, and which order these tests are running in. It'd be helpful for us to just have a hook that resets the overrides entirely to avoid the overhead of that state management.

I'm happy to contribute this myself as it looks like a fairly straightforward addition to `Evaluator` to be wrapped and surfaced in `StatsigServer` similar to `overrideGate`. Would a PR for that be accepted?

**Comment by tore-statsig** [comment]
Yes, we should definitely add this (I believe other sdks with overrides do have this functionality).  If you'd like to put up a PR we can take a look, otherwise we will get to it shortly

**Comment by neil176** [comment]
Thanks @tore-statsig ! I'll start on a PR this afternoon. Would you prefer a single method to clear all of these or a separate method for each?

```
gateOverrides
configOverrides
layerOverrides
```

**Comment by tore-statsig** [comment]
Nice!  One clear per entity type would be preferable, yes

**Comment by tore-statsig** [comment]
https://github.com/statsig-io/node-js-server-sdk/releases/tag/5.18.0

**Comment by tore-statsig** [comment]
Thanks @neil176 ! Published!

**Comment by neil176** [comment]
Thank you!

**Comment by neil176** [comment]
@tore-statsig  can `5.18.0` get released on NPM?

**Comment by kenny-statsig** [comment]
@neil176 Sorry about that, the release job seems to have failed. I manually released `5.18.0` to NPM.

**Comment by neil176** [comment]
No problem thank you again!
