### ISSUE TITLE
OutputLogger doesn't respect disableAllLogging flag

### ISSUE THREAD

**Issue by jkalberer** [statsig-io/node-js-server-sdk#43]
We're getting a ton of debug log spam from the `OutputLogger` starting with `statsigsdk`

Is `disableAllLogging` for something else?
I don't see the flag in your docs.

**Comment by tore-statsig** [comment]
I think both of these are missing from the docs - we will get that fixed.  I understand the confusion though `disableAllLogging` is for disabling logging to statsig servers (events, exposures, etc), not local.

I think for local logging you can use the log level or implement the logger interface to customize local output logging.  If our defaults aren't reasonable here though, we should update that as well
