### ISSUE TITLE
serverless and socket tls disconnection

### ISSUE THREAD

**Issue by shrynx** [statsig-io/node-js-server-sdk#45]
we are using [serverless](https://www.serverless.com/) framework
and our logs are constantly bombarded with such logs below

```l
FetchError: request to https://api.statsigcdn.com/v1/download_config_specs/secret-XXXXXXXXXXX.json?sinceTime=1717766609627 failed, reason: Client network socket disconnected before secure TLS connection was established\n at ClientRequest. (/node_modules/node-fetch/lib/index.js:1501:11)\n at ClientRequest.emit (node:events:529:35)\n at ClientRequest.emit (node:domain:489:12)\n at TLSSocket.socketErrorListener (node:_http_client:501:9)\n at TLSSocket.emit (node:events:517:28)\n at TLSSocket.emit (node:domain:489:12)\n at emitErrorNT (node:internal/streams/destroy:151:8)\n at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {\n type: 'system',\n errno: 'ECONNRESET',\n code: 'ECONNRESET'\n}\n
```

the setup code for serverless we have is

```js
const serverlessHandler = serverless(app);

export const handler = async (event: object, context: object) => {
  await Statsig.initialize(
    process.env.STATSIG_SERVER_KEY || "",
    { environment: "production" }
  );
  return await serverlessHandler(event, context);
};
```

**Comment by kenny-statsig** [comment]
@shrynx The request to `https://api.statsigcdn.com/v1/download_config_specs` is necessary for any SDK functionality. Unless you are using a [data adatper](https://docs.statsig.com/server/concepts/data_store#dataadapter-or-datastore) which is recommended for serverless environments. I'm not sure what your goal is but if what you really want to do is mute these logs, you can override the `console.log` via the [logger](https://github.com/statsig-io/node-js-server-sdk/blob/b0afe467e9be4fc76b202a598526a8e3020a2801/src/StatsigOptions.ts#L86) option. But note that the SDK wont function properly unless this error is properly addressed.
