### ISSUE TITLE
StatsigFetcher._retry breaks timeout logic

### ISSUE THREAD

**Issue by andrzej-woof** [statsig-io/node-js-server-sdk#49]
Hi, I believe handling of abort signal is broken in general.
First of all [StatsigFetcher._retry](https://github.com/statsig-io/node-js-server-sdk/blob/f9db2717943eea45453686bac3cb78d913f19a62/src/utils/StatsigFetcher.ts#L216) doesn't receive or pass that in any way. 
But even if it did it would have to create new signal each time, and since only `signal` is passed to the fetcher one cannot reliably know the timeout value with which it was constructed.

Consider the following scenario of invoking [StatsigServer.flush](https://github.com/statsig-io/node-js-server-sdk/blob/f9db2717943eea45453686bac3cb78d913f19a62/src/StatsigServer.ts#L522) function

```js
await Statsig.flush(100); // manually flush any unsent events
```

It takes timeout as parameter and an abort controller is created and `signal` is being passed further down. However if that request fails a retry request will be issued without any `signal` passed

**Comment by tore-statsig** [comment]
Thanks for the report, we are taking a look

**Comment by tore-statsig** [comment]
Fixed in https://github.com/statsig-io/node-js-server-sdk/releases/tag/5.25.1
